In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.decomposition import PCA
import pandas as pd
from sklearn.preprocessing import StandardScaler
from numpy.linalg import inv, qr, det
import nltk
import os
import scipy.cluster.hierarchy as shc

In [2]:
df=pd.read_excel('VAE1817_BSEV_F_Young1.xlsx')
df.head()

AGE_YRS  NUMDAYS  VAX_DOSE_SERIES  M/F  BIRTHDEF_Y/N  NUM_SYMPS  SYMP_SEV  \
0     35.0       18                1    1             0          2  2.000000   
2     52.0        3                2    1             0          1  0.000000   
3     11.0       52                1    1             0          2  0.000000   
4     16.0        0                1    0             0          3  1.333333   
5     11.0        0                1    0             0          2  0.000000   

   MEDS_Y/N  CILL_Y/N  HIST_Y/N    ...     AR  GM  LA  LG  LL  MO  NS  RA  RL  \
0         0         0         0    ...      0   0   0   0   0   0   0   1   0   
2         0         0         1    ...      0   0   0   0   0   0   0   1   0   
3         0         0         0    ...      0   0   1   0   0   0   0   0   0   
4         1         1         1    ...      0   0   0   0   0   0   0   1   0   
5         1         0         0    ...      0   0   1   0   0   0   0   0   0   

   SEVERITY  
0         1  
2         1  
3         1  
4         1  
5         0  

[5 rows x 107 columns]

df=df[[c for c in df if c not in ['SEVERITY']] + ['SEVERITY']]
df=df.drop('OTH',axis=1)
df.to_excel('VAERS2018_FORMATED4.xlsx')
df.head()

In [3]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# load data
array = df.values
X = array[:,0:-1]
Y = array[:,-1]
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])
fit.scores_.argsort()[-4:][::-1]

[1.736e+03 5.147e+04 3.449e+00 1.824e+01 4.176e+01 1.237e+00 4.715e+00
 8.971e+00 4.738e+01 4.167e+01 2.208e+00 1.618e+02 1.425e-01 5.702e-01
 1.806e+00 1.425e-01 1.425e-01 2.592e-01 1.215e-04 7.155e+00 4.029e-02
 2.369e+00       nan 7.015e+00 7.005e-01 6.017e-01 2.345e-02 1.425e-01
 8.378e-05 4.276e-01 1.195e+00 5.917e+00 2.309e-01 1.425e-01       nan
 7.015e+00 1.298e-01 5.925e-02 5.686e-01 4.185e-01 1.425e-01 2.747e+00
 3.847e-02 4.543e+00 1.425e-01 2.298e+00 1.425e-01 2.812e+00 3.633e-02
 7.015e+00 7.648e-01 9.820e-02 4.300e-02 2.851e-01 2.579e+00 8.039e+00
 4.276e-01 3.464e+00 3.102e-02 1.903e+00 2.797e-02 6.257e+00 5.184e-01
 3.371e+00 6.809e-01 1.425e-01 7.127e-01 1.691e-01 3.798e-01 3.412e+01
 3.908e-01 1.910e-01 5.556e-01 2.579e+00 2.851e+00 1.872e+01 2.298e+00
 3.984e+00 9.649e-02 6.102e+00 1.425e-01 8.630e+00 1.425e-01 1.425e-01
 4.968e+00 6.031e-01 9.013e-01 2.218e-02 1.425e-01 5.702e-01 7.959e-02
 1.940e-01 9.649e-02 1.425e-01 5.966e+00 3.118e+00 6.759e+00 7.752e-01
 3.469

array([22, 34,  1,  0], dtype=int64)

In [11]:
df.iloc[0:5,22]

0    0
2    0
3    0
4    0
5    0
Name: DTPIPV, dtype: int64

# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# load data
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pd.read_csv(url, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])
fit.scores_.argsort()[-4:][::-1]

dataframe.iloc[0:5,5]

In [5]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load data
array = df.values
X = array[:,0:-1]
Y = array[:,-1]
# feature extraction
model = LogisticRegression()
rfe = RFE(model, 4)
fit = rfe.fit(X, Y)
print("Num Features: ", fit.n_features_)
print("Selected Features: ", fit.support_)
print("Feature Ranking: ", fit.ranking_)

Num Features:  4
Selected Features:  [False False False False  True False False False False False False  True
 False False False False False False False False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False]
Feature Ranking:  [ 99 101  94  25   1 100  84  55  17   7  96   1  70  23  80  91  52  29
  87  18  86  13 102   6  93  89  41  57  88  20  48   1  30  82 103   5
  83  44  50  45  69  75  35  19  81  59  58   9  40   4  42  33  47  56
  14   1  26  43  36   8  67  46  21  11  61  27  15  38  37  12  60  79
  24   

In [6]:
count=0
for i in fit.support_:
    if i == True:
        print(count)
    count+=1

4
11
31
55


In [7]:
df.iloc[0:5,17]

0    0
2    0
3    0
4    0
5    0
Name: DT, dtype: int64

In [8]:
# Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.ensemble import ExtraTreesClassifier
array = df.values
X = array[:,0:-1]
Y = array[:,-1]
# feature extraction
model = ExtraTreesClassifier()
model.fit(X, Y)
print(model.feature_importances_)
model.feature_importances_.argsort()[-4:][::-1]

E:\Program Files (x86)\Anaconda\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


[1.705e-01 1.569e-01 5.361e-02 2.762e-02 3.166e-03 9.721e-02 1.074e-01
 2.623e-02 2.016e-02 2.430e-02 1.461e-02 2.647e-02 2.423e-05 1.878e-05
 9.677e-04 9.313e-07 7.194e-06 4.891e-04 5.040e-03 3.942e-03 4.499e-03
 2.157e-03 0.000e+00 5.502e-04 7.267e-03 9.415e-03 2.210e-03 1.536e-06
 2.371e-03 9.346e-05 1.416e-04 9.018e-04 3.902e-04 0.000e+00 0.000e+00
 4.163e-04 5.303e-03 5.659e-03 1.930e-03 4.280e-03 3.402e-05 3.026e-03
 5.146e-03 3.374e-03 1.814e-06 9.785e-04 7.749e-06 9.865e-04 3.402e-03
 5.669e-04 5.069e-03 4.296e-03 6.901e-03 3.736e-06 1.885e-04 1.469e-03
 9.883e-06 4.162e-03 6.238e-03 4.660e-04 3.607e-04 1.037e-03 5.646e-04
 1.963e-03 7.477e-03 3.532e-05 4.299e-05 1.648e-03 4.777e-03 8.088e-03
 1.686e-03 2.126e-04 1.657e-03 3.279e-04 1.080e-03 8.710e-03 5.636e-04
 7.842e-04 2.946e-05 7.012e-03 8.251e-06 6.006e-03 0.000e+00 1.849e-05
 5.031e-03 6.813e-04 8.616e-03 3.346e-03 3.638e-06 2.555e-05 5.557e-04
 1.235e-02 4.975e-05 1.270e-05 1.714e-03 6.262e-03 8.409e-03 5.548e-03
 1.065

array([0, 1, 6, 5], dtype=int64)

In [9]:
model.feature_importances_.argsort()[-10:][::-1]

array([ 0,  1,  6,  5,  2,  3, 11,  7,  9,  8], dtype=int64)

In [10]:
df.iloc[0:5,2]

0    1
2    2
3    1
4    1
5    1
Name: VAX_DOSE_SERIES, dtype: int64